@extends('layouts.app')
@section('title', 'Inicio')
@section('content')
<div class="page-heading"><div><div class="eyebrow red">TU LAVANDERÍA, A UN CLIC</div><h1>Hola, {{ explode(' ', auth()->user()->name)[0] }} <span class="greeting-dot">.</span></h1><p>Todo listo para un día más ligero.</p></div><div class="date-chip"><x-icon name="calendar"/> {{ now()->locale('es')->isoFormat('D [de] MMMM, YYYY') }}</div></div>
<section class="hero"><div class="hero-copy"><span class="hero-tag"><span></span> QUICK WASH · UNIVALLE</span><h2>{{ auth()->user()->isStaff() ? 'Cada lavado, bajo control.' : 'Menos espera. Más vida universitaria.' }}</h2><p>{{ auth()->user()->isStaff() ? 'Gestiona las reservas y mantén a los estudiantes al tanto de su ropa.' : 'Elige tu horario, reserva una máquina y deja las filas atrás. Nosotros te acompañamos en cada lavado.' }}</p><a class="button white" href="{{ route(auth()->user()->isStaff() ? 'reservations.index' : 'reservations.create') }}"><x-icon name="plus"/> {{ auth()->user()->isStaff() ? 'Gestionar reservas' : 'Hacer una reserva' }} <x-icon name="arrow"/></a></div><x-laundry-art/></section>
<div class="stats-grid">
<article class="stat-card"><span class="stat-icon rose"><x-icon name="calendar"/></span><div><span class="stat-label">Reservas activas</span><strong>{{ $active }} @unless(auth()->user()->isStaff())<small>/ 3</small>@endunless</strong><span class="stat-hint">{{ auth()->user()->isStaff() ? 'En toda la lavandería' : 'Organiza tus próximos lavados' }}</span></div></article>
<article class="stat-card"><span class="stat-icon green"><x-icon/></span><div><span class="stat-label">Máquinas habilitadas</span><strong>{{ $available }} <small>/ {{ $machines->count() }}</small></strong><span class="stat-hint">Disponibilidad según el turno</span></div></article>
<article class="stat-card"><span class="stat-icon amber"><x-icon name="spark"/></span><div><span class="stat-label">Lavados en proceso</span><strong>{{ $inProgress }}</strong><span class="stat-hint">{{ $inProgress ? 'El personal está atendiendo tus prendas' : 'Consulta tus turnos pendientes' }}</span></div></article>
<article class="stat-card"><span class="stat-icon gray"><x-icon name="check"/></span><div><span class="stat-label">Lavados finalizados</span><strong>{{ $completed }}</strong><span class="stat-hint">Un pendiente menos en tu día</span></div></article>
</div>

<div class="dashboard-columns"><div><section class="panel"><div class="section-heading"><div><h2>{{ auth()->user()->isStaff() ? 'Reservas recientes' : 'Mis últimas reservas' }}</h2><p>El estado de tus lavados, en un solo lugar.</p></div><a class="text-link" href="{{ route('reservations.index') }}">Ver todas <x-icon name="arrow"/></a></div>@include('partials.reservation-table', ['reservations' => $recent, 'compact' => true])</section>
<section class="panel machines-preview"><div class="section-heading"><div><h2>Nuestras máquinas</h2><p>Un espacio preparado para cuidar tu ropa.</p></div><a class="text-link" href="{{ route(auth()->user()->isStaff() ? 'machines.index' : 'reservations.create') }}">Ver máquinas <x-icon name="arrow"/></a></div><div class="mini-machines">@forelse($machines->take(4) as $machine)<div class="mini-machine"><span class="mini-washer"><x-icon/></span><strong>{{ $machine->name }}</strong><small>{{ $machine->capacity }} kg · {{ ucfirst($machine->type) }}</small><span class="status {{ $machine->status === 'disponible' ? 'listo' : 'pendiente' }}">{{ $machine->status === 'disponible' ? 'Habilitada' : 'Mantenimiento' }}</span></div>@empty<p class="muted">Todavía no hay máquinas registradas.</p>@endforelse</div></section></div>
<aside class="tips-panel"><span class="tip-icon"><x-icon name="spark"/></span><h2>Así de fácil.</h2><p>Tu ropa limpia en tres pasos.</p><div class="step"><span>01</span><div><strong>Elige tu turno</strong><p>Encuentra una máquina y un horario que te convenga.</p></div></div><div class="step"><span>02</span><div><strong>Acércate a la lavandería</strong><p>Llega a tiempo con tu ropa y tu código de reserva.</p></div></div><div class="step"><span>03</span><div><strong>Recoge y sigue tu día</strong><p>Consulta el estado. Cuando figure Esperando recogida, retírala y pulsa Recogido en Mis reservas.</p></div></div><div class="hours"><x-icon name="clock"/><div><strong>Horario de atención</strong><p>Todos los días · 08:00 a 20:00<br>Turnos de 60 minutos</p></div></div></aside></div>
@endsection
