BEGIN TRANSACTION;
CREATE TABLE "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE "machines" ("id" integer primary key autoincrement not null, "name" varchar not null, "type" varchar not null default 'lavadora', "capacity" integer not null, "location" varchar not null, "status" varchar not null default 'disponible', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
INSERT INTO "machines" VALUES(1,'Lavadora 01','lavadora',8,'Lavandería · Planta baja','disponible','2026-09-15 23:31:15','2026-09-15 23:31:15',NULL);
INSERT INTO "machines" VALUES(2,'Lavadora 02','lavadora',8,'Lavandería · Planta baja','disponible','2026-09-15 23:31:15','2026-09-15 23:31:15',NULL);
INSERT INTO "machines" VALUES(3,'Lavadora 03','lavadora',8,'Lavandería · Planta baja','disponible','2026-09-15 23:31:15','2026-09-15 23:31:15',NULL);
INSERT INTO "machines" VALUES(4,'Lavadora 04','lavadora',8,'Lavandería · Planta baja','mantenimiento','2026-09-15 23:31:15','2026-09-15 23:31:15',NULL);
INSERT INTO "machines" VALUES(5,'Secadora 05','secadora',10,'Lavandería · Planta baja','disponible','2026-09-15 23:31:15','2026-09-15 23:31:15',NULL);
INSERT INTO "machines" VALUES(6,'Secadora 06','secadora',10,'Lavandería · Planta baja','disponible','2026-09-15 23:31:15','2026-09-15 23:31:15',NULL);
CREATE TABLE "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO "migrations" VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO "migrations" VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO "migrations" VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO "migrations" VALUES(4,'2026_09_14_000001_create_quick_wash_tables',1);
INSERT INTO "migrations" VALUES(5,'2026_09_15_000001_align_reservations_with_exam',1);
CREATE TABLE "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE "reservation_slots" ("id" integer primary key autoincrement not null, "reservation_id" integer not null, "machine_id" integer not null, "starts_at" datetime not null, foreign key("reservation_id") references "reservations"("id") on delete cascade, foreign key("machine_id") references "machines"("id") on delete restrict);
INSERT INTO "reservation_slots" VALUES(1,1,1,'2026-09-16 10:00:00');
INSERT INTO "reservation_slots" VALUES(2,2,2,'2026-09-14 09:00:00');
INSERT INTO "reservation_slots" VALUES(3,3,3,'2026-09-12 14:00:00');
CREATE TABLE "reservations" ("id" integer primary key autoincrement not null, "user_id" integer not null, "machine_id" integer not null, "starts_at" datetime not null, "ends_at" datetime not null, "status" varchar not null default 'pendiente', "created_at" datetime, "updated_at" datetime, "garment_count" integer, foreign key("user_id") references "users"("id") on delete restrict, foreign key("machine_id") references "machines"("id") on delete restrict);
INSERT INTO "reservations" VALUES(1,1,1,'2026-09-16 10:00:00','2026-09-16 11:00:00','pendiente','2026-09-15 23:31:17','2026-09-15 23:31:17',8);
INSERT INTO "reservations" VALUES(2,1,2,'2026-09-14 09:00:00','2026-09-14 10:00:00','finalizada','2026-09-15 23:31:17','2026-09-15 23:31:17',9);
INSERT INTO "reservations" VALUES(3,1,3,'2026-09-12 14:00:00','2026-09-12 15:00:00','finalizada','2026-09-15 23:31:17','2026-09-15 23:31:17',10);
INSERT INTO "reservations" VALUES(4,1,1,'2026-09-11 11:00:00','2026-09-11 12:00:00','cancelada','2026-09-15 23:31:17','2026-09-15 23:31:17',11);
CREATE TABLE "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE TABLE "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "role" varchar not null default 'estudiante');
INSERT INTO "users" VALUES(1,'Alex Rivera','estudiante@est.univalle.edu',NULL,'$2y$12$Xt43b3I31C86h3T70En3X.fOFI2LjjqTczRkAYGc1aNMD1/3dvGXO',NULL,'2026-09-15 23:31:16','2026-09-15 23:31:16','estudiante');
INSERT INTO "users" VALUES(2,'María Flores','personal@quickwash.test',NULL,'$2y$12$VXVw3ouTRydGZW93JbIMd.g7BoxAex1hLUba0r8w8r51kVIhdr/oa',NULL,'2026-09-15 23:31:17','2026-09-15 23:31:17','personal');
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "machines_name_unique" on "machines" ("name");
CREATE INDEX "reservations_user_id_status_index" on "reservations" ("user_id", "status");
CREATE UNIQUE INDEX "reservation_slots_machine_id_starts_at_unique" on "reservation_slots" ("machine_id", "starts_at");
CREATE UNIQUE INDEX "reservation_slots_reservation_id_unique" on "reservation_slots" ("reservation_id");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('migrations',5);
INSERT INTO "sqlite_sequence" VALUES('machines',6);
INSERT INTO "sqlite_sequence" VALUES('users',2);
INSERT INTO "sqlite_sequence" VALUES('reservations',4);
INSERT INTO "sqlite_sequence" VALUES('reservation_slots',3);
COMMIT;
