@extends('layouts.app')
@section('title', auth()->user()->isStaff() ? 'Todas las reservas' : 'Mis reservas')
@section('content')
<div class="page-heading"><div><div class="eyebrow red">CADA LAVADO, ORGANIZADO</div><h1>{{ auth()->user()->isStaff() ? 'Todas las reservas' : 'Mis reservas' }}</h1><p>{{ auth()->user()->isStaff() ? 'Supervisa los lavados automáticos y las recogidas de los estudiantes.' : 'Consulta tus próximos turnos y el estado de tu ropa.' }}</p></div>@unless(auth()->user()->isStaff())<a class="button" href="{{ route('reservations.create') }}"><x-icon name="plus"/> Nueva reserva</a>@endunless</div>
<div class="inline-note"><x-icon name="info"/><span>El lavado comienza automáticamente a la hora reservada. Al terminar, pasa a Esperando recogida. Solo el estudiante puede pulsar Recogido para finalizar y liberar la máquina. Si la máquina sigue ocupada, el siguiente lavado espera y conserva sus 60 minutos.</span></div>
<p class="muted" id="live-status" role="status">Actualización automática cada 10 segundos · Horario de Bolivia</p>
<section class="panel"><form method="GET" class="filter-bar"><label class="search-field"><span>Buscar</span><input name="search" value="{{ request('search') }}" placeholder="Buscar por máquina o estudiante"></label><label>Estado<select name="status"><option value="">Todos los estados</option>@foreach(\App\Models\Reservation::LABELS as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></label><label>Fecha<input type="date" name="date" value="{{ request('date') }}"></label><button class="button secondary">Filtrar</button><a class="text-link" href="{{ route('reservations.index') }}">Limpiar</a></form><div id="live-reservations">@include('partials.reservation-table', ['compact' => false])<div class="pagination"><span>{{ $reservations->total() }} reserva(s)</span><div>@if($reservations->previousPageUrl())<a class="button small secondary" href="{{ $reservations->previousPageUrl() }}">Anterior</a>@endif<span>Página {{ $reservations->currentPage() }} de {{ $reservations->lastPage() }}</span>@if($reservations->nextPageUrl())<a class="button small secondary" href="{{ $reservations->nextPageUrl() }}">Siguiente</a>@endif</div></div></div></section>
<div class="inline-note"><x-icon name="info"/><span>{{ auth()->user()->isStaff() ? 'Puedes cancelar reservas pendientes antes de su horario. Solo el estudiante confirma su recogida.' : 'Puedes cancelar solo las reservas pendientes cuyo horario aún no haya comenzado. Retira tu ropa y pulsa Recogido para liberar la máquina.' }}</span><a class="text-link" href="{{ request()->fullUrl() }}">Actualizar</a></div>
@endsection
